### ISSUE TITLE
EthosConnect gets stuck in the "loading" status

### ISSUE THREAD

**Issue by channainfo** [EthosWallet/ethos-connect#28]
I was able to connect to the [Sui wallet](https://chrome.google.com/webstore/detail/sui-wallet/opcgpfmipidbgpenhmajoajpbobppdil) however after I refreshed the page it show the following errors

```
Unhandled Runtime Error
Error: Error fetching owned object: Error: RPC Error: Method not found for address 

Call Stack
JsonRpcProvider.eval
node_modules/@mysten/sui.js/dist/index.mjs (3554:0)
Generator.throw
<anonymous>
rejected
node_modules/@mysten/sui.js/dist/index.mjs (52:0)
```

Below is my nextjs page

```
export default function HomePage() {
  const { status, wallet } = ethos.useWallet();

  return (
    <EthosConnectProvider
      dappName='Joed'
      connectMessage='Your connect message goes here!'
      ethosConfiguration={{
        hideEmailSignIn: false, // defaults to false,
      }}
    >
      <Layout>
        <Seo />

        <main>
          <section className='bg-white'>
            <div>
              Status: {status}, address {wallet?.address}
            </div>
            <SignInButton> Connect Wallet </SignInButton>
          </section>
        </main>
      </Layout>
    </EthosConnectProvider>
  );
}
```
![Next js + Tailwind CSS + TypeScript Starter 2023-03-28 20-10-39](https://user-images.githubusercontent.com/4484749/228295576-c62c612b-8437-4e7d-8ff6-c21314977373.png)

My node modules

    "ethos-connect": "^0.0.106",
    "next": "^13.2.4",
    "react": "^18.2.0",

**Comment by jaredcosulich** [comment]
Ethos Connect version 0.0.107 which was just published has compatibility for Sui 0.29.0 - This might be the cause of the problem you are seeing.

**Comment by channainfo** [comment]
Thank you @jaredcosulich. But Ethos Connect  0.0.107 does not seem to fix the problem. the status is still stuck with the loading and when I clicked on the SignInButton, Ethos Connect did not recognize any wallets I have installed on my browser.

 
![Next js + Tailwind CSS + TypeScript Starter 2023-03-29 10-08-00](https://user-images.githubusercontent.com/4484749/228417007-ea7be1ab-9bda-411d-9986-286446087a75.png)

**Comment by jaredcosulich** [comment]
Are the wallets you have installed updated to the latest wallet standard? For example Ethos Wallet should be version 0.0.0.121 or higher

**Comment by channainfo** [comment]
@jaredcosulich After upgrading Ethos wallet to 0.0.0.121, Ethos Connect can display the wallets however I still face the same problem that the status from the react hook is always **loading**. The following error I got from Chrome console:
```
react_devtools_backend.js:2655 Error: RPC Validation Error: The response returned from RPC server does not match the TypeScript definition. This is likely because the SDK version is not compatible with the RPC server.
    at JsonRpcClient.requestWithType (index.mjs?3268:2083:1)
    at async JsonRpcProvider.getOwnedObjects (index.mjs?3268:3841:1)
    at async P (getWalletContents.js?ddd4:1:458)
    at async o (useAccount.js?d6a8:1:235)
```

Tested with:
- Ethos Wallet ( 0.0.0.121 )
- Ethos Connect ("ethos-connect": "0.0.107")

![Next js + Tailwind CSS + TypeScript Starter 2023-03-29 22-00-36](https://user-images.githubusercontent.com/4484749/228583267-73a9011d-a51a-40af-a4a1-0274112aeb4c.png)

**Comment by channainfo** [comment]
@jaredcosulich https://ethos-example-app.onrender.com/ works (see the attachment). 
From what I see, the example app uses Nextjs 12.2.4 and in my case, I am having nextjs 13.2.4. Is Ethos Connect not compatible with Nextjs 13.x?

![https---ethos-example-app onrender com 2023-03-29 22-52-26](https://user-images.githubusercontent.com/4484749/228598167-a9bf552c-0c42-49ac-837b-3fb8f104094a.png)

**Comment by jaredcosulich** [comment]
No, it is. https://ethoswallet.xyz uses `ethos-connect` and is a next.js 13 app. Does that work for you?

**Comment by jaredcosulich** [comment]
No problem. Would love to know what the problem is. We need to update the docs for the latest Sui v0.29.0 release so we might be able to add to them to help other people.

**Comment by jaredcosulich** [comment]
What does your EthosConfiguration look like?

**Comment by channainfo** [comment]
I found the issue. I had EthosConnectProvider and SignInButton in the same component (pages/index.tsx). After following the sample app by putting EthosConnectProvider in _app.tsx it works as expected.

**Comment by jaredcosulich** [comment]
Ah yes, that's easy to get tripped up on, but the SignInButton has to be within the context of the provider.
